# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
cr3_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1:
        p: 100
        d: 10
        i: 0.01
        i_clamp: 1
      joint2:
        p: 500
        d: 100
        i: 0.05
        i_clamp: 1
      joint3:
        p: 800
        d: 100
        i: 0.1
        i_clamp: 1
      joint4:
        p: 500
        d: 10
        i: 0.01
        i_clamp: 1
      joint5:
        p: 500
        d: 10
        i: 0.01
        i_clamp: 1
      joint6:
        p: 500
        d: 10
        i: 0.01
        i_clamp: 1
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0
        joint1: {trajectory: 0.1, goal: 0.1}
        joint2: {trajectory: 0.1, goal: 0.1}
        joint3: {trajectory: 0.1, goal: 0.1}
        joint4: {trajectory: 0.1, goal: 0.1}
        joint5: {trajectory: 0.1, goal: 0.1}
        joint6: {trajectory: 0.1, goal: 0.1}
    state_publish_rate: 25  
controller_list:
  - name: cr3_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6