darknet_ros_topic: /darknet_ros/bounding_boxes
output_bbx3d_topic: /darknet_ros_3d/bounding_boxes
point_cloud_topic: /camera/depth_registered/points
working_frame: camera_link
# working_frame: dummy_link
mininum_detection_thereshold: 0.2
minimum_probability: 0.2
interested_classes: ["chair","keyboard","laptop","sports ball","person","cell phone"]
