darknet_ros_topic: /cloud_pcd
output_bbx3d_topic: /darknet_ros_3d/bounding_boxes
point_cloud_topic: /camera/depth_registered/points
working_frame: camera_link
mininum_detection_thereshold: 0.2
minimum_probability: 0.2
interested_classes: ["bottle","person","laptop"]
