# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
cr3_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
      joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
      joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
      joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
      joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
      joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
    constraints:
        goal_time: 2.0
        stopped_velocity_tolerance: 0.1
        joint1: {trajectory: 1, goal: 1}
        joint2: {trajectory: 1, goal: 1}
        joint3: {trajectory: 1, goal: 1}
        joint4: {trajectory: 1, goal: 1}
        joint5: {trajectory: 1, goal: 1}
        joint6: {trajectory: 1, goal: 1}
    state_publish_rate: 25  
controller_list:
  - name: cr3_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6