dodo_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: elbow_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: gripper_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  gazebo_ros_control/pid_gains:
    shoulder_pan_joint: {p: 100.0, i: 0.01, d: 10.0}
    shoulder_pitch_joint: {p: 100.0, i: 0.01, d: 10.0}
    elbow_pitch_joint: {p: 100.0, i: 0.01, d: 10.0}
    wrist_roll_joint: {p: 100.0, i: 0.01, d: 10.0}
    wrist_pitch_joint: {p: 100.0, i: 0.1, d: 10.0}
    gripper_roll_joint: {p: 100.0, i: 0.1, d: 10.0}
    finger_joint1: {p: 100.0, i: 0.1, d: 10.0}
    finger_joint2: {p: 100.0, i: 0.1, d: 10.0}

 
